### ISSUE TITLE
session ticket is never stored 

### ISSUE THREAD

**Issue by thelaui** [PlayFab/JavaScriptSDK#1]
When using any of the API's functions that should store the session ticket, the actual retrieved ticked never is considered for being saved in `exports.settings.session_ticket`.

The erroneous line is 

```javascript
settings.session_ticket = result.SessionTicket != null ? settings.session_ticket : settings.session_ticket;
```

and should be corrected to

```javascript
settings.session_ticket = result.SessionTicket != null ? result.SessionTicket : settings.session_ticket;
```

**Comment by zac-playfab** [comment]
Resolved as of October 2015.
