### ISSUE TITLE
If script is loaded on a page with SSL, this call fails http://code.jquery.com/jquery-1.7.1.min.js

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/JavaScriptSDK#61]
http://code.jquery.com/jquery-1.7.1.min.js

should be called as

https://code.jquery.com/jquery-1.7.1.min.js

(https)

Manually changed and resolves this part, but causes this issue:  https://github.com/PlayFab/JavaScriptSDK/issues/62

**Comment by pgilmorepf** [comment]
The use of HTTP or HTTPS should match wherever this file is hosted.  This file isn't meant to be hosted, so it's not strictly useful either way.

However, I think HTTPS as a general rule is a better choice, so your suggestion will be published in the next revision.
