### ISSUE TITLE
PlayFabApiTest.js:589 null ", Failed to save test report to CloudScript: " "jbuild_0" "

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/JavaScriptSDK#62]
PlayFabApiTest.js:589 null ", Failed to save test report to CloudScript: " "jbuild_0" "
```
" "[
    {
        "name": "jbuild_0",
        "tests": 0,
        "failures": 0,
        "errors": 0,
        "skipped": 0,
        "time": 0.003,
        "timestamp": "2016-06-20T05:56:58.185Z",
        "testResults": []
    }
]"
```
PlayFabApiTest.js:92 testTitleData input file did not parse correctly

**Comment by dylanh724** [comment]
Comments in the JSON file seem to destroy the test app --

Need to instruct users to REMOVE the comments after they enter info, or add JS to parse it out.

**Comment by pgilmorepf** [comment]
That file is our internal testing file, and it's only meant to be run from PlayFabApiTest.html.
You should not be using that file in your project.

If you are trying to run our test framework:
Are all the tests passing?  Are you trying to set up some kind of automated system?

Your comment about SSL:
SSL/TLS, PlayFabSdk, and the PlayFabApiTest.js test code are all separate things.  For proper security, PlayFab requires that you're running TLS 1.2.
https://en.wikipedia.org/wiki/Transport_Layer_Security
https://github.com/PlayFab/JavaScriptSDK#2-prerequisites

This section describes that the test framework is independent of the SDK:
https://github.com/PlayFab/JavaScriptSDK#3-example-project-playfabapitesthtml--playfabapitestjs
But I admit, the readme doesn't properly describe how to use the SDK itself.  I will try to remedy this.

To address your reported issue specifically, I will need additional information:
Are you trying to run our automated test framework?
Are you trying to build a game project of your own?
Are you running the tests from the provided PlayFabApiTest.html?

**Comment by pgilmorepf** [comment]
As an extra note:
I'm going to close this issue, so if you continue to have issues, the best place to get help is on our forums:
https://community.playfab.com/index.html

This location is for issues with the SDK itself. The forum is better for troubleshooting issues specifically with your project, and you will almost certainly get a faster response there.
