### ISSUE TITLE
Installing SDK via npm or bower

### ISSUE THREAD

**Issue by vuk** [PlayFab/JavaScriptSDK#79]
Is there an option to install SDK to project via npm or bower package managers? If not, is it planned?

**Comment by pgilmorepf** [comment]
For now we have the JavaScriptSDK available via CDN for client applications (suggested to use in development, but not in release):
https://blog.playfab.com/blog/playfab-now-serving-javascript-sdk-via-cdn

Our existing NPM package is for Node.js environments, so if you need that, you can find it here:
https://www.npmjs.com/package/playfab-sdk
But that's more for server-side applications.

Finally, your request is reasonable, but we won't be doing it right away.  I will leave this task open until we have it, but I give no guarantees if or when we'll do it.

**Comment by vuk** [comment]
Ok. Thanks for the info

**Comment by pgilmorepf** [comment]
Hello!

We're working on a submission for this SDK into NPM.
Check out the pull requests for more info:
https://github.com/PlayFab/JavaSDK/pulls
https://github.com/PlayFab/JavaScriptSDK/pull/80
https://github.com/PlayFab/JavaScriptSDK/pull/81

Let us know if that resolves your request.  Thanks!

**Comment by vuk** [comment]
Yes. I think that settles it. Cool. Thanks

**Comment by pgilmorepf** [comment]
Ok. It should be available now!
