### ISSUE TITLE
LoginXXX calls do not pass customData and extraHeaders to ExecuteRequest.

### ISSUE THREAD

**Issue by markseminatore** [PlayFab/JavaScriptSDK#83]
## Expected Behavior

result.CustomData contains the `customData object` passed to the LoginXXX API

The `extraHeaders` object passed to the LoginXXX API is used in the REST request

## Observed Behavior

result.CustomData is `undefined`

`extraHeaders` is not used for LoginXXX calls

## Steps to Reproduce

1. Call any of the LoginXXX APIs and pass in a customData object.  For example { "foo": "bar" }
2. Set a breakpoint in the callback and when hit examine the value of result.CustomData.

## Remark

A result of this behavior is that you are unable to use `extraHeaders` or `customData` with the various LoginXXX calls.

**Comment by pgilmorepf** [comment]
Fixed:
https://github.com/PlayFab/SDKGenerator/commit/7a6dfb80ba53208ee5c1d9ffa7ea7d0995779d4f
