### ISSUE TITLE
Can't use TypeScript definitions

### ISSUE THREAD

**Issue by nerdError** [PlayFab/JavaScriptSDK#94]
![image](https://user-images.githubusercontent.com/55310192/150927343-b38f517b-b017-4bee-93ed-8f789f7120d2.png)

I'm not sure why it happens, maybe I do miss something. Probably, there must be ``types`` property in ``package.json``, as described here: [How to get your d.ts files to users](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

But if I copy type definitions to my project manually, it works fine. So problem is in a package settings or something, not in files itself.

**Comment by jordan-playfab** [comment]
Hi @nerdError, it's true that our TypeScript situation isn't ideal. You'll have to make a few changes to get TypeScript working. The open source project [Vanguard Outrider](https://github.com/PlayFab/vanguard-outrider) has the sample code you'll need. Here are the changes, summarized:

### tsconfig.json
``` json
"files": ["./src/index.d.ts"]
```

### src/index.d.ts
``` typescript
/// <reference path="../node_modules/playfab-web-sdk/src/Typings/PlayFab/PlayFabClientApi.d.ts" />
/// <reference path="../node_modules/playfab-web-sdk/src/Typings/PlayFab/PlayFabAdminApi.d.ts" />
```

### src/app/shared/playfab.ts
``` typescript
import "playfab-web-sdk/src/PlayFab/PlayFabClientApi.js";

// then you can use e.g.

PlayFab.ClientApi.LoginWithCustomID({
    TitleId: titleId,
    CustomId: customId,
    CreateAccount: true,
}, (result, problem) => {
    if(!is.null(problem)) {
        return error(problem.errorMessage);
    }

    if(result.code === 200) {
        success(result.data);
    }
    else {
        error(result.errorMessage);
    }
});
```

**Comment by toddbellMSFT** [comment]
At this time, [jordan-playfab's](https://github.com/jordan-playfab) work around is the current recommended solution.
